/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import DAO.DisciplinaDao;
import Model.Disciplina;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author diego
 */
public class Disciplinas extends javax.swing.JFrame {

    /**
     * Creates new form Disciplinas
     */
    public Disciplinas() {
        initComponents();
    }

    public void listar(int opt, String valor) {
        DisciplinaDao d = new DisciplinaDao();

        if (valor == null) {
            List<Disciplina> disciplinas = d.listRC(null, opt);
            if (disciplinas.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Não há disciplinas cadastradas!.", "Erro", JOptionPane.ERROR_MESSAGE);
            }
            String texto = "";
            for (Disciplina dis : disciplinas) {
                texto = texto + dis.retornaDisciplinas();
            }
            jTextAreaDisciplinas.setText(texto);
        } else {
            List<Disciplina> disciplinas = d.listRC(valor, opt);
            if (disciplinas.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Não há disciplinas cadastradas!.", "Erro", JOptionPane.ERROR_MESSAGE);
            }
            String texto = "";
            for (Disciplina dis : disciplinas) {
                texto = texto + dis.retornaDisciplinas();
            }
            jTextAreaDisciplinas.setText(texto);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelDisciplinas = new javax.swing.JPanel();
        jLabelTituloDisciplinas = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaDisciplinas = new javax.swing.JTextArea();
        jButtonListarDisciplinas = new javax.swing.JButton();
        jButtonListarDisciplinasPorRegistro = new javax.swing.JButton();
        jTextFieldListarPorRegistro = new javax.swing.JTextField();
        jLabelCodigo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(555, 364));

        jPanelDisciplinas.setBackground(new java.awt.Color(102, 102, 102));
        jPanelDisciplinas.setMinimumSize(new java.awt.Dimension(0, 0));

        jLabelTituloDisciplinas.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelTituloDisciplinas.setForeground(new java.awt.Color(255, 0, 51));
        jLabelTituloDisciplinas.setText("DISCIPLINAS");

        jTextAreaDisciplinas.setColumns(20);
        jTextAreaDisciplinas.setRows(5);
        jTextAreaDisciplinas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextAreaDisciplinasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTextAreaDisciplinas);

        jButtonListarDisciplinas.setBackground(new java.awt.Color(255, 0, 51));
        jButtonListarDisciplinas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonListarDisciplinas.setForeground(new java.awt.Color(255, 255, 255));
        jButtonListarDisciplinas.setText("LISTAR TUDO");
        jButtonListarDisciplinas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListarDisciplinasActionPerformed(evt);
            }
        });

        jButtonListarDisciplinasPorRegistro.setBackground(new java.awt.Color(255, 0, 51));
        jButtonListarDisciplinasPorRegistro.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonListarDisciplinasPorRegistro.setForeground(new java.awt.Color(255, 255, 255));
        jButtonListarDisciplinasPorRegistro.setText("BUSCAR POR REGISTRO");
        jButtonListarDisciplinasPorRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListarDisciplinasPorRegistroActionPerformed(evt);
            }
        });

        jTextFieldListarPorRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldListarPorRegistroActionPerformed(evt);
            }
        });

        jLabelCodigo.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabelCodigo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCodigo.setText("Código");

        javax.swing.GroupLayout jPanelDisciplinasLayout = new javax.swing.GroupLayout(jPanelDisciplinas);
        jPanelDisciplinas.setLayout(jPanelDisciplinasLayout);
        jPanelDisciplinasLayout.setHorizontalGroup(
            jPanelDisciplinasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDisciplinasLayout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addGroup(jPanelDisciplinasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelDisciplinasLayout.createSequentialGroup()
                        .addGroup(jPanelDisciplinasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelDisciplinasLayout.createSequentialGroup()
                                .addComponent(jLabelCodigo)
                                .addGap(134, 134, 134)
                                .addComponent(jLabelTituloDisciplinas, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9))
                            .addGroup(jPanelDisciplinasLayout.createSequentialGroup()
                                .addComponent(jTextFieldListarPorRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonListarDisciplinasPorRegistro)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonListarDisciplinas)))
                .addGap(42, 42, 42))
        );
        jPanelDisciplinasLayout.setVerticalGroup(
            jPanelDisciplinasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDisciplinasLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanelDisciplinasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTituloDisciplinas)
                    .addComponent(jLabelCodigo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDisciplinasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonListarDisciplinas)
                    .addComponent(jButtonListarDisciplinasPorRegistro)
                    .addComponent(jTextFieldListarPorRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelDisciplinas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelDisciplinas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(569, 400));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextAreaDisciplinasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextAreaDisciplinasMouseClicked


    }//GEN-LAST:event_jTextAreaDisciplinasMouseClicked

    private void jButtonListarDisciplinasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListarDisciplinasActionPerformed
        listar(2, null);
    }//GEN-LAST:event_jButtonListarDisciplinasActionPerformed

    private void jButtonListarDisciplinasPorRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListarDisciplinasPorRegistroActionPerformed
        listar(1, jTextFieldListarPorRegistro.getText());
    }//GEN-LAST:event_jButtonListarDisciplinasPorRegistroActionPerformed

    private void jTextFieldListarPorRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldListarPorRegistroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldListarPorRegistroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Disciplinas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Disciplinas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Disciplinas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Disciplinas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Disciplinas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonListarDisciplinas;
    private javax.swing.JButton jButtonListarDisciplinasPorRegistro;
    private javax.swing.JLabel jLabelCodigo;
    private javax.swing.JLabel jLabelTituloDisciplinas;
    private javax.swing.JPanel jPanelDisciplinas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaDisciplinas;
    private javax.swing.JTextField jTextFieldListarPorRegistro;
    // End of variables declaration//GEN-END:variables
}
