package View;

import DAO.JDBCUTIL;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 * @author fabricio
 */
public class JanelaRelatorio extends javax.swing.JFrame {

    Connection connection = null;

    public static final String pasta_relatorios = System.getProperty("user.dir") + "/src/Relatorios/";
    public static final File file_relatorio_professor_fonte = new File(pasta_relatorios, "RelatorioProfessor.jrxml");
    public static final File file_relatorio_professor_compilado = new File(pasta_relatorios, "RelatorioProfessor.jasper");
    public static final File relatorio_professor_pdf = new File(pasta_relatorios, "RelatorioProfessor.pdf");
    
    public static final File file_relatorio_consulta_tarefa_parametro_fonte = new File(pasta_relatorios, "RelatorioConsultaTarefa.jrxml");
    public static final File file_relatorio_consulta_tarefa_parametro_compilado = new File(pasta_relatorios, "RelatorioConsultaTarefa.jasper");
    public static final File relatorio_consulta_tarefa_parametro_pdf = new File(pasta_relatorios, "RelatorioConsultaTarefa.pdf");
    
    
    public static final File file_relatorio_variavel_group_fonte = new File(pasta_relatorios, "RelatorioVariavelGroup.jrxml");
    public static final File file_relatorio_variavel_group_compilado = new File(pasta_relatorios, "RelatorioVariavelGroup.jasper");
    public static final File relatorio_variavel_group_pdf = new File(pasta_relatorios, "RelatorioVariavelGroup.pdf");
    
    
    private Map constroiParametrosTarefa() {
        Map params = new HashMap();
        String cod = JOptionPane.showInputDialog(
                this,
                "Digite um código para o relatório",
                "Entrada de dados",
                JOptionPane.QUESTION_MESSAGE);

        params.put("codigo", cod);
        return params;
    }
    
    public JanelaRelatorio() {
        try {
            
            String path = System.getProperty("user.dir");
            File config_file = new File(path, "src/DAO/configuracaobd.properties");
            DAO.JDBCUTIL.init(config_file);
            connection = DAO.JDBCUTIL.getConnection();
            System.out.println("CONECTADO!!.");
        } catch (ClassNotFoundException | SQLException | IOException erro) {
            System.out.println("Erro ao criar conexao com o BD.");
        }
        initComponents();
        System.out.println(System.getProperties());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabelTituloConsultar = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("GERAR RELATÓRIO PROFESSOR");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("PDF");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 0, 0));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("GERAR RELATÓRIO TAREFA (PARÂMETRO)");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(255, 0, 0));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("PDF");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabelTituloConsultar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelTituloConsultar.setForeground(new java.awt.Color(255, 0, 51));
        jLabelTituloConsultar.setText("RELATÓRIOS");

        jButton5.setBackground(new java.awt.Color(255, 0, 7));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("GERAR RELATÓRIO DE ATIVIDADES SEM CONCLUSÃO");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(255, 0, 0));
        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("PDF");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addComponent(jLabelTituloConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(69, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4))
                    .addComponent(jButton6))
                .addGap(62, 62, 62))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabelTituloConsultar)
                .addGap(70, 70, 70)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton6))
                .addContainerGap(147, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked

        JasperPrint impressao;
        try {
            FileInputStream arquivo = new FileInputStream(file_relatorio_professor_fonte);
            JasperReport relatorio
                    = JasperCompileManager.compileReport(arquivo);
            impressao = JasperFillManager.fillReport(
                    relatorio,
                    null,
                    connection);
            JasperViewer.viewReport(impressao);
        } catch (JRException | FileNotFoundException erro) {
            System.err.println("Não foi possível exportar o relatório.\n\n" + erro);
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        JasperPrint impressao;
        try {
            FileInputStream arquivo = new FileInputStream(file_relatorio_professor_fonte);
            JasperReport relatorio
                    = JasperCompileManager.compileReport(arquivo);
            impressao = JasperFillManager.fillReport(
                    relatorio,
                    null,
                    connection);
            JasperExportManager.exportReportToPdfFile(impressao, relatorio_professor_pdf.getAbsolutePath());
            JOptionPane.showMessageDialog(this, "Gerado o arquivo com sucesso: " + relatorio_professor_pdf.getAbsolutePath());
        } catch (FileNotFoundException | JRException erro) {
            System.err.println("Não foi possível exportar o relatório.\n\n" + erro);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        JasperPrint impressao;
        try {
            FileInputStream arquivo = new FileInputStream(file_relatorio_consulta_tarefa_parametro_fonte);
            JasperReport relatorio = JasperCompileManager.compileReport(arquivo);
            impressao = JasperFillManager.fillReport(
                relatorio,//arquivo .jasper
                constroiParametrosTarefa(),
                connection);
            JasperViewer.viewReport(impressao);
        } catch (FileNotFoundException | JRException ex) {
            System.err.println("Não foi possível exportar o relatório.\n\n");
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        JasperPrint impressao;
        try {
            FileInputStream arquivo = new FileInputStream(file_relatorio_consulta_tarefa_parametro_fonte);
            JasperReport relatorio = JasperCompileManager.compileReport(arquivo);
            impressao = JasperFillManager.fillReport(
                relatorio,
                constroiParametrosTarefa(),
                connection);
            JasperExportManager.exportReportToPdfFile(impressao, relatorio_consulta_tarefa_parametro_pdf.getAbsolutePath());
            JOptionPane.showMessageDialog(this, "Gerado o arquivo " + relatorio_consulta_tarefa_parametro_pdf.getAbsolutePath());
        } catch (FileNotFoundException | JRException ex) {
            System.err.println("Não foi possível exportar o relatório.\n\n");
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        JasperPrint impressao;
        try {
            FileInputStream arquivo = new FileInputStream(file_relatorio_variavel_group_fonte);
            JasperReport relatorio
                    = JasperCompileManager.compileReport(arquivo);
            impressao = JasperFillManager.fillReport(
                    relatorio,
                    null,
                    connection);
            JasperViewer.viewReport(impressao);
        } catch (JRException | FileNotFoundException erro) {
            System.err.println("Não foi possível exportar o relatório.\n\n" + erro);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
                JasperPrint impressao;
        try {
            FileInputStream arquivo = new FileInputStream(file_relatorio_variavel_group_fonte);
            JasperReport relatorio
                    = JasperCompileManager.compileReport(arquivo);
            impressao = JasperFillManager.fillReport(
                    relatorio,
                    null,
                    connection);
            JasperExportManager.exportReportToPdfFile(impressao, relatorio_variavel_group_pdf.getAbsolutePath());
            JOptionPane.showMessageDialog(this, "Gerado o arquivo com sucesso: " + relatorio_variavel_group_pdf.getAbsolutePath());
        } catch (FileNotFoundException | JRException erro) {
            System.err.println("Não foi possível exportar o relatório.\n\n" + erro);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaRelatorio.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaRelatorio.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaRelatorio.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaRelatorio.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaRelatorio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabelTituloConsultar;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
